#!/bin/sh
# SVN UPDATE

REVISION=$*
HTTP_ROOT="http://garage68.ru.local" # Для информации в конце

MYSQL_HOST="localhost"
MYSQL_USER="garage68"
MYSQL_DB="garage68"
MYSQL_PASS="garage68"
ARCHIVER="bzip2"
DUMP_NAME="dump"

SECOND_MYSQL_HOST="localhost"
SECOND_MYSQL_USER="garage68forum"
SECOND_MYSQL_DB="garage68forum"
SECOND_MYSQL_PASS="garage68forum"
SECOND_ARCHIVER="bzip2"
SECOND_DUMP_NAME="forum/dump"

############################################


svn up # Загрузка данных HEAD из репозитория в хранилище локальной копии
if  [ -n "${REVISION}" ]; then
	echo REVISION: ${REVISION}
    REV_PARAM=" -r ${REVISION}"
    echo REV_PARAM: ${REV_PARAM}
    svn merge -rHEAD:${REVISION} .	# Слияние данных HEAD и нужной ревизии репозитория, загрузка в локальное хранилище 
fi
#----#touch dump.sql
#----#rm dump.sql
#----#svn revert
#----#svn resolve --accept base ./dump.sql




svn status | awk '{if ($1=="?") print $2}' | xargs rm -rf # удаление лишнего из локальной копии на основе данных хранилища
#svn up ${REV_PARAM}
svn status | awk '{if ($1=="M") print $2}' | xargs svn revert --depth=infinity # возврат файлов на основе данных локальной копии


#----#svn resolve --accept base ./dump.sql
#mysqladmin -uforum  -pforum drop -f forum
#mysqladmin -uforum  -pforum create forum
#mysql -uforum  -pforum forum  < ./dump.sql

### FIRST ###
if [ "${ARCHIVER}" = "gzip" ]; then
    ARCH_EXT="gz"
    TAR_OPT="z"
    ARCH_APP="/usr/bin/gzip"
fi
if [ "${ARCHIVER}" = "bzip2" ]; then
    ARCH_EXT="bz2"
    TAR_OPT="j"
    ARCH_APP="/usr/bin/bzip2"
fi
mysqladmin -u${MYSQL_USER}  -p${MYSQL_PASS} drop -f ${MYSQL_DB}
mysqladmin -u${MYSQL_USER}  -p${MYSQL_PASS} create ${MYSQL_DB}
${ARCH_APP} -dc "./${DUMP_NAME}.sql.${ARCH_EXT}" | mysql -u${MYSQL_USER} -p${MYSQL_PASS} ${MYSQL_DB}
#############

### SECOND ###
if [ "${SECOND_ARCHIVER}" = "gzip" ]; then
    ARCH_EXT="gz"
    TAR_OPT="z"
    ARCH_APP="/usr/bin/gzip"
fi
if [ "${SECOND_ARCHIVER}" = "bzip2" ]; then
    ARCH_EXT="bz2"
    TAR_OPT="j"
    ARCH_APP="/usr/bin/bzip2"
fi
mysqladmin -u${SECOND_MYSQL_USER}  -p${SECOND_MYSQL_PASS} drop -f ${SECOND_MYSQL_DB}
mysqladmin -u${SECOND_MYSQL_USER}  -p${SECOND_MYSQL_PASS} create ${SECOND_MYSQL_DB}
${ARCH_APP} -dc "./${SECOND_DUMP_NAME}.sql.${ARCH_EXT}" | mysql -u${SECOND_MYSQL_USER} -p${SECOND_MYSQL_PASS} ${SECOND_MYSQL_DB}
#############

echo "Дамп залили! Окрывайте сайт на локалке."
echo ${HTTP_ROOT}
