#!/bin/sh
### Скрипт игнорирования файлов и дерикторий в проекте на базе .svnignore в корне
#Устанавливаем разделитель строк
SAVEIFS=${IFS}
IFS='
'
IGNORE_FILE_CONTENT=`cat .svnignore`
IFS=${SAVEIFS}	#возвращаем разделитель строк

#echo "${IGNORE_FILE_CONTENT}"
IGNORE_FILE_CONTENT=`echo "${IGNORE_FILE_CONTENT}" | sed 's/\*/AsTeRiSk/g'`

echo "==============================================="

INDEX0=0
for CURRENT_STRING in ${IGNORE_FILE_CONTENT}; do
	CURRENT_STRING=`echo "${CURRENT_STRING}" | sed 's/AsTeRiSk/\*/g'`
	echo "Строка: ${CURRENT_STRING}"
	FILE=`echo "${CURRENT_STRING}" | awk -F \/ '{print $NF}'`
	echo "File: ${FILE}" 
	DIR=`echo ${CURRENT_STRING} | awk -F \/ '{$NF = ""; print $0}'`
	echo "Directory: ${DIR}"
	RESULT_DIR=''
	for SUBDIR in ${DIR}; do
		RESULT_DIR=${RESULT_DIR}${SUBDIR}/
	done
	if [ "${RESULT_DIR}" = "" -o  "${RESULT_DIR}" = "." ]; then
		RESULT_DIR="./"
	fi
	RESULT_DIR=${RESULT_DIR}		# ЧТО ЗА ХРЕНЬ?
	echo "Итоговая директория: ${RESULT_DIR}"
	DIRS=$(echo -e ${DIRS} ${RESULT_DIR})
	export DIR_LIST${INDEX0}="${RESULT_DIR}"
	#echo INDEX0: ${INDEX0}
	let INDEX0=${INDEX0}+1 > /dev/null
	echo "++++++++++++++++++++++++++++++++++++++="
done
echo "INDEX0 (количество элементов исходного массива): ${INDEX0}"
######### Делаем последовательность индексов ########
NOW=0
while [ "${NOW}" -le "${INDEX0}" ]
do
	#echo NOW indexes: ${NOW}
	INDEXES=`echo ${INDEXES} ${NOW}`
	let "NOW = NOW + 1" > /dev/null 2>&1
done
#echo INDEXES: ${INDEXES}

######### Выводим отсортированный и уникализированный массив в переменную ########

UNIC_DIRS=`for NOW in ${INDEXES}
do
	eval echo "$"DIR_LIST${NOW}
	export DIR_LIST${NOW}="DIR_LIST${NOW}"
done | sort -u` 
echo ${UNIC_DIRS}

######### Получаем индекс из нового массива ########

INDEX_NOW=0
for STRING_CONTENT in ${UNIC_DIRS}; do
	DIR_FOR_SET=""
	touch /tmp/.svnignore
	rm /tmp/.svnignore
	touch /tmp/.svnignore

	STRING_CONTENT=`echo "${STRING_CONTENT}"`
	echo "Директория для обработки: ${STRING_CONTENT}"
	export DIR_LIST${INDEX_NOW}="${STRING_CONTENT}"
	echo ${INDEX_NOW}
	INDEX1=${INDEX_NOW}
	


	# Внутри цикла перебора уникализированного массива перебираем всё содержимое файла, ища сопоставленные директории
	INDEX2=0
	for CURRENT_STRING in ${IGNORE_FILE_CONTENT}; do
		CURRENT_STRING=`echo "${CURRENT_STRING}" | sed 's/AsTeRiSk/\*/g'`
		echo "Строка: ${CURRENT_STRING}"
		FILE=`echo "${CURRENT_STRING}" | awk -F \/ '{print $NF}'`
		echo "File: ${FILE}" 
		DIR=`echo ${CURRENT_STRING} | awk -F \/ '{$NF = ""; print $0}'`
		RESULT_DIR=''
		for SUBDIR in ${DIR}; do
			RESULT_DIR=${RESULT_DIR}${SUBDIR}/
		done
		if [ "${RESULT_DIR}" = "" -o  "${RESULT_DIR}" = "." ]; then
			RESULT_DIR="./"
		fi
		RESULT_DIR=${RESULT_DIR}  # ЧТО ЗА ХРЕНЬ?

		if [ "${RESULT_DIR}" = ${STRING_CONTENT} ]; then
			echo "Совпала директория: ${RESULT_DIR}"
			echo "${RESULT_DIR}${FILE}" >> /tmp/.svnignore 
			DIR_FOR_SET="${RESULT_DIR}"
			
		fi		
		
		DIRS=$(echo -e ${DIRS} ${RESULT_DIR})
		export NAME${INDEX2}="${RESULT_DIR}"
		let INDEX2=${INDEX2}+1 > /dev/null
		echo "-----------------------------------------"
	done
	echo "svn propset svn:ignore -F /tmp/.svnignore ${DIR_FOR_SET}"
	svn propset svn:ignore -F /tmp/.svnignore ${DIR_FOR_SET}
	#echo "++++++++++++++++++++++++++++++++++++++++++++++" >> /tmp/.svnignore 
	echo "++++++++++++++++++++++++++++++++++++++++++++++"
	let INDEX_NOW=${INDEX_NOW}+1 > /dev/null
done
#echo "INDEX1 (количество элементов уникализированного массива): ${INDEX1}" # Индекс на выходе

### Выше получили проиндексированный уникализированный отфильтрованый массив директорий





